export default {
  // 验证登录有关
  WAIT_FOR_RESPONSE: 'WAIT_FOR_RESPONSE',
  AUTH_SUCCESS_AND_SAVE_TOKEN: 'AUTH_SUCCESS_AND_SAVE_TOKEN',
  AUTH_FAILED: 'AUTH_FAILED',
  AFTER_RESPONSE: 'AFTER_RESPONSE'
}
