export default {
  // 验证登录有关
  WAIT_FOR_RESPONSE: 'WAIT_FOR_RESPONSE',
  AUTH_SUCCESS_AND_SAVE_TOKEN: 'AUTH_SUCCESS_AND_SAVE_TOKEN',
  AUTH_FAILED: 'AUTH_FAILED',
  AFTER_RESPONSE: 'AFTER_RESPONSE',
  LOGOUT_AND_CLEAR_TOKEN: 'LOGOUT_AND_CLEAR_TOKEN',
  GET_AND_SAVE_LOCATION: 'GET_AND_SAVE_LOCATION',
  // 应用状态有关
  CAN_NOT_USE_MAP_SEARCH: 'CAN_NOT_USE_MAP_SEARCH'
}
